---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyquant)
library(tidyverse)
library(dplyr)
library(plyr)
library(bsts)
library(matrixStats)
```

```{r}
#df = daily %>% dplyr::select(stock_id, date, adjusted) %>% as_tibble ()# connecting to db 
#load("tot_df.Rdata")
load("sp500_df.Rdata")
#load("df.Rdata")
 
#df = tot_df
df = sp500_df
### As log produce NAS in some cases, these are adjusted to zero Becoue the NAs' are linked to stock being delisted etc
df[is.na(df)] = 0 # setting nas to zero  intead of omiting them

#df = dplyr::group_by(df, symbol) 

tot_df = NULL

df = df %>% dplyr::filter(adjusted > 0) 
df = df %>% dplyr::filter(close > 0) 

df = dplyr::select(df, symbol, date, adjusted)

#Sticking with relativly "fresh" stocks, as older periods often have alot of NAs and holes in them.
df = df %>% dplyr::filter(date > "1980-01-01")

# These stocks are removed due to wierd data. in total_df
unwanted = c("TOPS", "CEI", "OSAT", "INPX", "ABIO", "NUWE", "NSPR")
  
df = dplyr::filter(df, !symbol %in% unwanted)

sp500_df = NULL

unwanted = NULL


#Need to remove stocks that have adjusted zero or below!!!! 
#  also remvoe stocks with zero close

#  Try remove extreme high valued stocks
  
```


```{r}
##
## CREATING A MONTHLY DATASET ! 
##

#df_date = df_date as.Date.POSIXct(df_date, tryFormat = "%Y-%m-%d")
df$date = df$date %>% as.Date()

#df = dplyr::filter(df, date > "2002-12-31")

month_day = LastDayInMonth(df$date) %>% as.Date()

 # This is due to extreme amounts of NAs in 1970s-1960 to get a better dataset. 

df = dplyr::filter(df, date == month_day) #Filters out all other dates for the month except last one

df$ranking_start = df$date %m-% months(12) # Start ranking of the portf, -12 months (as per MC paper)

day(df$ranking_start) = days_in_month(df$ranking_start) #Se day of data to last day of month

df$ranking_end = df$date %m-% months(2) # Per MC paper subtract two months

day(df$ranking_end) = days_in_month(df$ranking_end) # set day of the date = last day of the month

df = df %>% group_by(symbol)
```

```{r}
# Return calculation for each stock in. More accurate then the "simple" lead - var /var method 
# Normal methods gives high random scores, as it tries to calculate with next col
# This method returns NA when there is no other date to calculate to (no next lead)

return_calculations = function(portfolio){
  reb_month =  unique(portfolio$date)
  reb_stock = unique(portfolio$symbol)
  temp_holder = NULL
  temp_holder2 = NULL
  pb = txtProgressBar(min = 0, max = length(reb_stock), initial = 0, style = 3)
  count = 1
    for (j in 1:length(reb_stock)){
      temp_holder = portfolio %>% filter(symbol == reb_stock[j])
      temp_holder$return  = (((lead(temp_holder$adjusted) - temp_holder$adjusted))  / temp_holder$adjusted)
      temp_holder2 = rbind(temp_holder,temp_holder2) 
      count = count + 1
      setTxtProgressBar(pb,count)
        }
  return(temp_holder2)
}  

df = return_calculations(df)
```

```{r}
dfa= data.table::data.table(df) #making a "working" table

dfa$shifted_date<-dfa$date %m+% months(1) # Shifting the date with one month   

day(dfa$shifted_date)<-days_in_month(dfa$shifted_date) # Sets last day of months to shifted month  

df[is.na(df)] = 0 #set nas' to zero
dfa[is.na(dfa)] = 0 #set nas' to zero

month_day = NULL #free up ram
```

```{r}

##
# Cross checking that both tables are in tibble
##
df = df %>% as.tibble()
dfa = dfa %>% as.tibble()

#names(dfa)[names(dfa) == "close"] = "close.x"

x = c("symbol", "shifted_date", "return") # creates variables to copy later  
return_cols = c() # Makes an empty vector where we get the returns 

pb = txtProgressBar(min = 1, max = 12, initial = 0, style = 3)
count = 1
for(i in c(2:12)){ # eleven months return 
    dfa$shifted_date = dfa$date %m+% months(i) # shift by i months
    day(dfa$shifted_date) = days_in_month(dfa$shifted_date) # Provides shift date with end of month
  
    df = merge(df, # merge return using the shifted date
                     dfa[x],
                     by.x=c("symbol", "date"),
                     by.y=c("symbol", "shifted_date"),
                     all.x=TRUE
                     )
    
    names(df)[names(df) == "return.x"] <- "return" # correct the column names
    names(df)[names(df) == "return.y"] <-paste0("return", i)# adding the roling returns for months  
    return_cols<-c(return_cols, paste0("return", i)) # adds the new cols in a list to remove from set later
    count = count + 1 # just a counter for progress bar 
    setTxtProgressBar(pb, count) # initiates the prog bar
}


return_cols # Checking return cols 
df$available_returns = rowSums(!is.na(df[,return_cols[2:11]])) # compute number of available returns

df$cum_return = rowProds(1+as.matrix(df[,return_cols[2:11]]), na.rm=T) # compute cumulative product
df = df[, -c(7:17)] # WARNING HARD CODED! Removes the m_rets previously calculated  

#df<-df[, !return_cols[2:11]] # drop return_cols (not needed anymore)
glimpse(df) #checking the data
```


```{r, putting into monthly deciles}
# This will first only take the stocks with more or equal to 8 month of return
# Then it will Normalize the numbers, by taking the cumalative return and devide by availability to get more accurate numbers
# Then we will take every stock per month and drop it into a docile based on cumalative returns 

#
# NB! line 187 and 188 containes cum_ret, which i belive we should use for this projects 
# Change those two outs, to use return will lead to a BIAS forward looking! But it gets better resaults.

decile_seperation = function(portfolio){
  portfolio = portfolio %>% filter(available_returns >= 8) # Above 8 monthly returns in ranking 
  portfolio$cum_return = portfolio$cum_return / portfolio$available_returns #Normalising 
  reb_month =  unique(portfolio$date) # Finding all unique dates 
  temp_holder = NULL # Empty working var
  temp_holder2 = NULL # Empty working var 
  temp_holder3 = NULL # Empty working var 
  temp_holder4 = NULL # Empty working var
  pb = txtProgressBar(min = 0, max = length(reb_month), initial = 0, style = 3) # progress bar
  count = 1 #counter for usage in progress bar
    for (j in 1:length(reb_month)){ # Takes all months with the mentioned criteria above.
      temp_holder = portfolio %>% filter(date == reb_month[j]) # filter each dates so we have one specific month
      temp_holder2 = cut(temp_holder$return, # put it into dociles, based on monthly return
          quantile(temp_holder$return,probs=seq(from=0,to=1,by=1/10),na.rm =T),
          include.lowest=TRUE, 
          labels=FALSE)
       temp_holder3= add_column(temp_holder ,as.tibble(temp_holder2)) # adds the decile score to the table 
       temp_holder4= bind_rows(temp_holder3 ,temp_holder4)  # Binds the score and the folder for a stock and date
       count = count + 1 # Adds 1 to the counter for progressbar 
       setTxtProgressBar(pb,count) # Starting the progress bar
    }  
  return(temp_holder4) # Returns from function a entire dataset with quantiles attached.
}  

dfa = as.tibble(decile_seperation(df)) # calls the function on tibble df, and saves as dfa  

names(dfa)[names(dfa) == "value"] <- "quantile" # Renames the colume value to quantile.  

```


```{r, warning = FALSE}
top = dfa %>% dplyr::filter(quantile == 10) %>% arrange(date) # making the best performance portf
mid = dfa %>% dplyr::filter(quantile == 5) %>% arrange(date)  # worst performance portfolio based 
bot = dfa %>% dplyr::filter(quantile == 1) %>% arrange(date)  # worst performance portfolio based 
```


```{r, warning = FALSE}

###
### Calculates returns on specific portfolios, invest 1 dollar in time Zero and does compounding 
###### 
selecter = c("symbol", "date", "return") # Variables to have in top and bot tibble
top = dplyr::select(top,selecter) # Selects from selecter
mid = dplyr::select(mid,selecter) # Selects from selecter
bot = dplyr::select(bot,selecter) # Selects from selecter

cumalative_ret_portfolio = function (portfolio){ # Defining function
reb_month =  unique(portfolio$date) # finds each re-balancing months from the portfolio
tot_ret = c() # Empthy vector 
  for (i in 1:length(reb_month)){ # for each date we have in the portfolio do this 
    if (i == 1){  # First round do this 
    z = portfolio %>% filter(reb_month[i] == portfolio$date) # Select the first date on the list, filter out the rest
    ret = (1+z$return) * (1/nrow(z))  # Investing 1 dollar divided by stocks multiplied with returns
    tot_ret[i]  = sum(ret) # Summarize all the returns from investing one dollar 
    }
    if (i > 1){ # When its beyond start date, (t+1). Do the following
    z = portfolio %>% filter(reb_month[i] == portfolio$date) # Filter out the dates not needed
    temp = tot_ret / nrow(z) # devide what we earned in the previous period on the numbers of stocks to reinvest  
    ret = (1+z$return) * temp # multiply the investments dollar from previous step with the returns 
    tot_ret[i]  = sum(ret) # Sum it all up 
    }
  }
return(tot_ret) #returns the calculations out of the loop
}

total_port_ret = function (portfolio){ # Just a filter function to makesure everything has return over 0 
  portfolio = portfolio %>% filter(return != 0) # Returns can not be zero
  tot_ret = (cumalative_ret_portfolio(portfolio)) # calls the previous function (We run a function in a function)
  return(tot_ret) # Returns the total returns 
} 


##
## This section retrives a string of numbers (return per rebalancing period)
##
top_score = total_port_ret(top) # runs the script on top portfolio 
mid_score = total_port_ret(mid) # runs on bot portf.
bot_score = total_port_ret(bot) # runs on bot portf.
```

```{r}
##
# Takes the dates and merges then with the scores, making a more user friendly experience
##
scores = function (portfolio, parent_portfolio){ # makes function
  portfolio = portfolio %>% as.tibble # converts the score into a tibble for easier processing 
  colnames(portfolio)[1] = "cum_rets"  # Rename the cumalative returns 
  dates = parent_portfolio$date  %>% as.Date() %>% unique() # Find the dates from the parent calulations (pre last function)
  portfolio$date  =  dates  # takes the dates and put them into tbe portfolio
  return(portfolio) # Returns resaults 

} 

top_score_reb = scores(top_score, top) #Calls the function on the score and the parrent 
mid_score_reb = scores(mid_score, mid) # same but for mid score 
bot_score_reb = scores(bot_score, bot) # same but for bot score 
```


```{r}
top_score_reb %>% arrange(desc(date)) # Shows table from prev, but starting at the highest date decending downwards
mid_score_reb %>% arrange(desc(date)) # Same but for mid
bot_score_reb %>% arrange(desc(date)) # Same but for bot.
```

```{r}
# Not implimented yet 

ggplot(top_score_reb, aes(x = date)) +
       theme(legend.position = "top") +
       geom_line(aes(y = cum_rets ), color = "darkred") + 
       labs(x = 'Date',
       y = 'Cumulative Returns',
       title = 'Portfolio Cumulative Returns') +
    scale_y_continuous(breaks = seq(0,100,10)) +
    scale_x_date()#date_breaks = '10 year',
               #date_labels = '%Y')

```


