---
title: "Calculation of portfolios"
output: nils
---

```{r}
library(tidyquant)
library(tidyquant)
library(tidyverse)
library(dplyr)
library(plyr)
library(slider)
library(bsts)
library(matrixStats)
```

# ```{r}
#   library(doParallel)
#   library(snow)
#   library(doSNOW)
# cl <- makeCluster(detectCores()-1, type = "SOCK")
#  
# call_cluster_init = function(cl){
#  registerDoParallel(cl)
# }
# ```

```{r}
db <- dbConnect(RPostgres::Postgres(), dbname = "stock_db")

overview <- tbl(db, "overview")
daily = tbl(db, "daily")

df = daily %>% dplyr::select(stock_id, date, close) %>% as_tibble ()# connecting to db 

df$date = df$date %>% as.POSIXct()  

df = na.omit(df)
# df = overview %>% dplyr::filter(ipo_year == 2021) %>% dplyr::filter(exchange == "NASDAQ")
# df

# dbWriteTable(db, "daily", value = df, overwrite = TRUE, append= F, row.names = FALSE)

```


```{r}
##
## CREATING A MONTHLY DATASET ! 
##


#df_date = df_date as.Date.POSIXct(df_date, tryFormat = "%Y-%m-%d")

month_day = LastDayInMonth(df$date) %>% as.Date()

#elect (Convert(date, '2018-04-01'))
df$date = df$date %>% as.Date()  

df = df %>% filter(date == month_day) #Filters out all other dates for the month except last one

df$ranking_start = df$date %m-% months(12) # Start ranking of the portf, -12 months (as per MC paper)

day(df$ranking_start) = days_in_month(df$ranking_start) #Se day of data to last day of month

df$ranking_end = df$date %m-% months(2) # Per MC paper subtract two months

day(df$ranking_end) = days_in_month(df$ranking_end) # set day of the date = last day of the month

dfa= data.table::data.table(df) #making a "working" table
dfa$shifted_date<-dfa$date %m+% months(1) # Shifting the date with one month      
day(dfa$shifted_date)<-days_in_month(dfa$shifted_date) # Sets last day of months to shifted month  

dfa[is.na(dfa)] = 0 #set nas' to zero

month_day = NULL
```


```{r}
gaps= c(1) #c(1,7,30) # daily, weekly, monthly, return #### SET TO ONE AS THIS IS MONTHLY DATASET

dfa = dfa %>% group_by(stock_id) %>% arrange(date) #Ordering and sorting the data 

returns = function(gaps){(df$close - lead(df$close, n= gaps)) / lead(df$close,n = gaps)} # Return function, gives return per month pr stock (roling returns)

rets = as.data.frame(lapply(gaps,returns)) # Run function on the gaps(1) to get returns

#colnames(rets)[1] <- "d_ret" # Renaming cols 
#colnames(rets)[2] <- "w_ret"
colnames(rets)[1] <- "m_ret" # Gives correct names 

# df_temp = dfa %>% # Adding cumalative returns 
#   mutate(cr = cumprod(1 + rets$m_ret)) 

#dfa = cbind(dfa, d_ret = rets[1], w_ret = rets[2], m_ret = rets[3], cr = df_temp$cr) # binding all calculated data to dfa

dfa = cbind(dfa, d_ret = rets[1])#, cr = df_temp$cr) # Binding CR and monthly return to main dataset 

head(dfa) # Checking the DFA to make sure we got everything we need

rets=NULL
df_temp = NULL
gaps = NULL
```

```{r}
######
## OLD CODE, WAS USED TO CALC 1,7,30 DAYS RETURN. NOW SET IS MONTHLY.
###
# goal is to check for monthly 8 monthly returns over 11 month 

# gaps= c(1,7,30) # daily, weekly, monthly, return
# 
# dfa = dfa %>% group_by(symbol) %>% arrange(date) #Ordering and sorting the data 
# 
# returns = function(gaps){(df$close - lead(df$close, n= gaps)) / lead(df$close,n = gaps)} # Return function
# 
# rets = as.data.frame(lapply(gaps,returns))

#dfa$shifted_date<-dfa$date %m+% months(1) # Making a column with +1 month shift as of the time lag needed for formations date
```


```{r}
#names(dfa)[names(dfa) == "close"] = "close.x"

x = c("stock_id", "shifted_date", "m_ret") # creates variables to copy later  
return_cols = c() # Makes an empty vector where we get the returns 

#packs_needed = c("dplyr", "tidyverse") #redundant info, was built for foreach loop

for(i in c(2:12)){ # eleven months return 
    dfa$shifted_date = dfa$date %m+% months(i) # shift by i months
    day(dfa$shifted_date) = days_in_month(dfa$shifted_date) # Provides shift date with end of month
    
    df = merge(df, # merge return using the shifted date
                     dfa[x],
                     by.x=c("stock_id", "date"),
                     by.y=c("stock_id", "shifted_date"),
                     all.x=TRUE
                     )
    
    names(df)[names(df) == "m_ret.x"] <- "m_ret" # correct the column names
    names(df)[names(df) == "m_ret.y"] <-paste0("m_ret", i)# adding the roling returns for months  
    return_cols<-c(return_cols, paste0("m_ret", i)) # adds the new cols in a list to remove from set later
}


return_cols # Checking return cols 
df$available_returns = rowSums(!is.na(df[,return_cols[2:11]])) # compute number of available returns
df

dfa=NULL # frees memory, dfa is no longer needed  
df$cum_return = rowProds(1+as.matrix(df[,return_cols[2:11]]), na.rm=T) # compute cumulative product
#df = df[, -c(8:17)] # WARNING HARD CODED! Removes the m_rets previously calculated  

#df<-df[, !return_cols[2:11]] # drop return_cols (not needed anymore)
#return_cols=NULL
#df_temp = NULL
#rets = NULL
#month_day = NULL
glimpse(df) #checking the data
```


```{r}
library(data.table)
dfa = df

# remove rows which have available_returns < 8 (less then 8 monthly return within the search)
dfa = dfa %>% filter(available_returns >= 8) # Provides the highest momentum stocks 
glimpse(dfa) # Rechecking table 

# normalize using the number of available returns
dfa$cum_return = dfa$cum_return / dfa$available_returns

# cut returns for each date into deciles to determine winner/loser portfolios
dfa$quantile = cut(dfa$cum_return,
    quantile(dfa$cum_return,probs=seq(from=0,to=1,by=1/10),na.rm =T),
    include.lowest=TRUE, 
    labels=FALSE)

top = dfa %>% filter(quantile == 10) # making the best performance portf 
top = top %>% arrange(date) # sorting after date  
#top$cr_ret = top$close - lead(top$close) / lead(top$close) # Adds returns IDK if this will work here !!!!

#####funk her#####

reb_month_top =  unique(top$date)
#holder = c()

for (i in 1:reb_month_top){ 
  top_portf = top[1:3] %>% filter(date == as.Date(reb_month_top[i]))
  print(top_portf)
}

#ret_port = function(top_portf){
  for (i in 1:nrow(top_portf)){
    x = df %>% filter(date == top_portf$date[i]) # all stock on the investment day within the 10th quantile
    y = x %>% filter(stock_id == top_portf$stock_id[i])# The specific stock to invest in 
    z = df %>% filter(stock_id == y[1,1]) # all data for the specific stock from x
    
    
    m = x[1,2]  %m+% months(1) # returns the stock plus one month 
    n = df %>% filter(stock_id == z[1,1]) %>% filter (date == m) # locates the return for this stock
    ret = (y$close  - n$close  / n$close) #### This is DELTA !!!! NOT PERCENTAGE!  
    av =top_portf$returns[i]  = ret
    holder[i] = ret
    print (ret)
    #top_portf = cbind(top_portf,as.matrix(holder))
    #return(top_portf)
  }

#}

test = function(portfolio){ 
  reb_month_top =  unique(top$date)
    for (j in 1:reb_month_top){ 
      portfolio = top[1:3] %>% filter(date == as.Date(reb_month_top[j]))
        for (i in 1:nrow(portfolio)){
            x =df %>% filter(date == portfolio$date[i])%>% filter(stock_id == portfolio$stock_id[i])# The specific stock to invest 
            z = df %>% filter(stock_id == x[1,1]) %>%  filter(date > portfolio[i,2])
            m = z[1,2]   # returns the stock plus one month 
            n = df %>% filter(stock_id == z[1,1]) %>% filter (date == m) # locates the return for this stock
            ret = (x$close   - n$close  / n$close) #### This is DELTA !!!! NOT PERCENTAGE!  
            portfolio$returns[i]  = ret
            print (ret)
            #top_portf = cbind(top_portf,as.matrix(holder))
            #return(top_portf)
  }
  }
}

test(top_portf)
  
EW_top 
  
  top_portf %>% mutate(p_cr = cumprod(1+))
  return(returns)
}

top = top[1:3] %>% mutate(portfolio_return = cumprod(1 + rets$m_ret))
    
df_temp = df %>% # Adding cumalative returns 
 mutate(portfolio_return = cumprod(1 + rets$m_ret))

names(df)[names(df) == "m_ret.y"] <-paste0("m_ret", i)# adding the roling returns for months
    
  }) 
  return(y)
}

    
  lead(df$close[1])
  EW_top * = top_portf$close[1] -  
  
})

så går det en måned, 
Da tar vi og kalkulrer hva vi har tjent per stock. 
Som blir da EW_top * med return for neste måned.
så kjører vi cumprod av dette. 

vi kalkulerer return. som da blir summen av returns 

dfa$shifted_date = dfa$date %m+% months(1)

returns = (top_portf$close - lead(df$close, n= 1)) / lead(df$close,n = 1)


bot = dfa %>% filter(quantile == 1) # "worst performing stocks 

#quant_portf = merge (bot, top, by.x = "date", by.y = "date") # just added them together (this is not used for anything yet)

#plotting the data, Get strange numbers. 
ggplot(top, aes(x = date)) +
       theme(legend.position = "top") +
       geom_smooth(aes(y = cum_return), color = "darkred") + 
       labs(x = 'Date',       labs(x = 'Date',
       y = 'Cumulative Returns',
       title = 'Portfolio Cumulative Returns') +
    scale_y_continuous(breaks = seq(0,50000,5000)) +
    scale_x_date())#date_breaks = '10 year',
               #date_labels = '%Y')
##
##
## SOMEONE NEEDS TO CHECK THE FLOW ! `
##



```
